// <auto-generated />
using BT_CodeFirst_QuanLyQuanCafe;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BT_CodeFirst_QuanLyQuanCafe.Migrations
{
    [DbContext(typeof(CafeDbContext))]
    [Migration("20260407072328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BT_CodeFirst_QuanLyQuanCafe.Models.LoaiMon", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiMons");
                });

            modelBuilder.Entity("BT_CodeFirst_QuanLyQuanCafe.Models.MonAn", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMon"));

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMon");

                    b.HasIndex("MaLoai");

                    b.ToTable("MonAns");
                });

            modelBuilder.Entity("BT_CodeFirst_QuanLyQuanCafe.Models.MonAn", b =>
                {
                    b.HasOne("BT_CodeFirst_QuanLyQuanCafe.Models.LoaiMon", "LoaiMon")
                        .WithMany("MonAns")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiMon");
                });

            modelBuilder.Entity("BT_CodeFirst_QuanLyQuanCafe.Models.LoaiMon", b =>
                {
                    b.Navigation("MonAns");
                });
#pragma warning restore 612, 618
        }
    }
}
